# Generated by Django 5.2.1 on 2025-05-27 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.CharField(blank=True, max_length=200, null=True)),
                ('folio', models.CharField(blank=True, max_length=200, null=True)),
                ('tienda', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('abonado', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('tipo', models.CharField(max_length=100)),
                ('extraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraccion.extraccion')),
            ],
        ),
    ]
