# Generated by Django 5.2.1 on 2025-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
    ]
